In [1]:
import pandas as pd
import numpy as np

km = 'KCAT'
df = pd.read_csv('../../data/EITLEM_KCAT_T.csv')

# 删除Temperature列中包含NaN的行
df.dropna(subset=['Temperature'], inplace=True)

# 重命名列
df.rename(columns={'Value': 'kcat', 'Sequence': 'seq', 'Smiles': 'smiles'}, inplace=True)

# 计算温度相关的列
Temp_K = [float(T) + 273.15 for T in df['Temperature']]
Inv_Temp = [1 / (float(T) + 273.15) for T in df['Temperature']]

# 归一化函数
def scale_minmax(array, x_min, x_max):
    '''
    Normalize the feature as (x - x_min) / (x_max - x_min).
    '''
    scaled_array = [(x - x_min) / (x_max - x_min) for x in array]
    return scaled_array

# 计算归一化后的温度
T_K_norm = scale_minmax(Temp_K, min(Temp_K), max(Temp_K))
inv_T_norm = scale_minmax(Inv_Temp, min(Inv_Temp), max(Inv_Temp))

# 将归一化后的温度添加到DataFrame
df['Temp_K'] = Temp_K
df['Inv_Temp'] = Inv_Temp
df['Temp_K_norm'] = T_K_norm
df['Inv_Temp_norm'] = inv_T_norm

# 保存结果到CSV文件（可选）
df.to_csv('./data/EITLEM_{}_all.csv'.format(km), index=False)

df

,ECNumber,Organism,Substrate,seq,smiles,kcat,type,source,Test,pH,Temperature,Temp_K,Inv_Temp,Temp_K_norm,Inv_Temp_norm
1,2.7.7.27,Escherichia coli,ATP,MVSLEKNDHLMLARQLPLKSVALILAGGRGTRLKDLTNKRAKPAVH...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...,371.200,mutant,custom,0,8.0,37.0,310.15,0.003224,0.37,0.554843
2,1.4.3.4,Homo sapiens,kynuramine,MENQEKASIAGHMFDVVVIGGGISGLSAAKLLTEYGVSVLVLEARD...,CCC1(c2ccccc2)CCC(=O)NC1=O,2.500,mutant,custom,0,7.2,30.0,303.15,0.003299,0.30,0.630727
4,1.3.1.3,Rattus norvegicus,NADPH,MNLSTANHHIPLNDGNSIPIIGLGTYSDPRPVPGKTFIAVKTAIDE...,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,0.010,wild,dlkcat,0,7.4,25.0,298.15,0.003354,0.25,0.687112
6,4.2.3.121,Lavandula angustifolia,geranyl diphosphate,MSIISMHVGILNRPAAYNHLRNLDRRASKPRHVSSTAAATRLRVSC...,CC(C)=CCC/C(C)=C/COP(=O)(O)OP(=O)(O)O,0.012,wild,custom,0,7.5,23.0,296.15,0.003377,0.23,0.710199
7,3.4.11.18,Escherichia coli,L-Met-PSI[C(O)S]Gly-L-Phe,MAISIKTPEDIEKMRVAGRLAAEVLEMIEPYVKPGVSTGELDRICN...,CSCC[C@H](N)C(=O)SCC(=O)N[C@@H](Cc1ccccc1)C(=O)O,30.800,mutant,custom,0,7.0,22.0,295.15,0.003388,0.22,0.721860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34771,1.2.99.7,Megalodesulfovibrio gigas,cinnamaldehyde,MIQKVITVNGIEQNLFVDAEALLSDVLRQQLGLTGVKVGCEQGQCG...,O=C/C=C/c1ccccc1,0.580,wild,custom,1,7.6,35.0,308.15,0.003245,0.35,0.576172
34774,2.4.1.49,Thermoclostridium stercorarium,4-nitrophenyl beta-D-glucoside,MRYGYFDEKAREYVITRPDTPTPWINYIGNGKYGGIVTNTGGGYSF...,O=[N+]([O-])c1ccc(O[C@@H]2O[C@H](CO)[C@@H](O)[...,19.600,wild,custom,1,6.5,45.0,318.15,0.003143,0.45,0.472207
34776,3.1.3.8,Aspergillus niger,myo-inositol hexakisphosphate disodium salt,MGVSAVLLPLYLLSGVTSGLAVPASRNQSTCDTVDQGYQCFSETSH...,O=P([O-])(O)O[C@@H]1[C@@H](OP(=O)(O)O)[C@H](OP...,281.000,wild,custom,1,5.5,50.0,323.15,0.003095,0.50,0.422637
34777,2.6.1.19,Escherichia coli,L-Aspartate,MNSNKELMQRRSQAIPRGVGQIHPIFADRAENCRVWDVEGREYLDF...,NC(CC(=O)O)C(=O)O,0.073,mutant,dlkcat,1,7.8,25.0,298.15,0.003354,0.25,0.687112
34780,1.1.1.405,Haemophilus influenzae,D-ribulose 5-phosphate,MNKNKNIGIILAGGVGSAMGLGYPKQFSKIAGKTALEHTLAIFQEH...,O=C(CO)[C@H](O)[C@H](O)COP(=O)(O)O,6.800,mutant,custom,1,7.2,25.0,298.15,0.003354,0.25,0.687112

In [2]:
df.drop(columns=['Test'], inplace=True)
from sklearn.model_selection import train_test_split
# train_df = df[df['Test'] == 0]
# test_df = df[df['Test'] == 1]
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
print(train_df.shape, test_df.shape)
train_df

(17101, 14) (4276, 14)

,ECNumber,Organism,Substrate,seq,smiles,kcat,type,source,pH,Temperature,Temp_K,Inv_Temp,Temp_K_norm,Inv_Temp_norm
30800,6.3.4.2,Lactococcus lactis,NH3,MSTKYIFVTGGGTSSMGKGIVAASLGRLLKNRGLKVTVQKFDPYLN...,N,1.80000,mutant,dlkcat,8.0,30.0,303.15,0.003299,0.30,0.630727
21872,5.4.2.6,Lactococcus lactis,beta-D-glucose 1-phosphate,MFKAVLFDLDGVITDTAEYHFRAWKALAEEIGINGVDRQFNEQLKG...,O=P(O)(O)O[C@@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C...,0.00384,mutant,custom,7.0,25.0,298.15,0.003354,0.25,0.687112
1478,2.7.1.2,Methylotuvimicrobium alcaliphilum,D-glucose,MILAGDIGGTKTTLALLSKNEHGLITLQQEQTFSSVEFPEFDEVLD...,OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O,257.70000,wild,custom,9.5,30.0,303.15,0.003299,0.30,0.630727
17482,3.1.1.88,Sphingobium sp.,cyhalothrin,MTVTDIILIHGALNRGACYDAVVPLLEARGYRVHAPDLTGHTPGDG...,CC1(C)C(/C=C(\Cl)C(F)(F)F)C1C(=O)OC(C#N)c1cccc...,1.28000,wild,custom,7.5,37.0,310.15,0.003224,0.37,0.554843
26969,3.4.21.53,Homo sapiens,FRETN 89-98,MAASTGYVRLWGAARCWVLRRPMLAAAGGRVPTAAGAWLLRGQRTC...,CCC(C)C(NC(=O)CNC(=O)C(CCCNC(=N)N)NC(=O)C(N)Cc...,6.63000,wild,custom,8.0,37.0,310.15,0.003224,0.37,0.554843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18208,3.5.1.14,Homo sapiens,N-acetyl-glycine,MTSKGPEEEHPSVTLFRQYLRIRTVQPKPDYGAAVAFFEETARQLG...,CC1(C)O[C@H]2CC(=O)OC[C@]23[C@H]2CC[C@@]4(C)[C...,31.70000,wild,custom,7.4,25.0,298.15,0.003354,0.25,0.687112
19339,2.5.1.18,Escherichia coli,"1-chloro-2,4-dinitrobenzene",MKLFYKPGACSLASHITLRESGKDFTLVSVDLMKKRLENGDDYFAV...,O=[N+]([O-])c1ccc(Cl)c([N+](=O)[O-])c1,4.80000,mutant,custom,6.5,25.0,298.15,0.003354,0.25,0.687112
8660,3.6.1.27,Vibrio vulnificus,farnesyl diphosphate,MSYFEAFVLALIQGLTEFLPISASAHLILPSAILGWEDQGLAFDVA...,CC(C)=CCC/C(C)=C/CC/C(C)=C/COP(=O)(O)OP(=O)(O)O,1.67000,mutant,custom,7.5,37.0,310.15,0.003224,0.37,0.554843
1352,4.1.1.49,Leishmania major,phosphoenolpyruvate,MAPIIHRNLTAPELVQWALKLEKDTKLSARGALCVLSYAKTGRSPR...,C=C(OP(=O)(O)O)C(=O)O,37.78000,mutant,custom,7.4,37.0,310.15,0.003224,0.37,0.554843
25477,5.3.1.4,Bacillus licheniformis,L-arabinose,MLTTGKKEFWFVVGSQHLYGEETLAEVRAHAQAMTDALNESAVLPY...,O=C[C@H](O)[C@@H](O)[C@@H](O)CO,38.90000,mutant,custom,7.5,50.0,323.15,0.003095,0.50,0.422637

In [3]:
train_df['Test'] = 0
test_df['Test'] = 1
train_df.to_csv('./data/EITLEM_{}_train.csv'.format(km), index=False)
test_df.to_csv('./data/EITLEM_{}_test.csv'.format(km), index=False)

In [4]:
all_df = pd.concat([train_df, test_df])
all_df.to_csv('./data/EITLEM_{}_all_new_split.csv'.format(km), index=False)

之后接train.sh